export const ADMIN_EXPERIENCE_MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB
export const ADMIN_EXPERIENCE_MAX_FILE_SIZE_MB = 5;

const ADMIN_EXPERIENCE_EXTENSIONS = {
  PNG: "png",
  JPG: "jpg",
  JPEG: "jpeg",
  WEBP: "webp",
} as const;

export const ADMIN_EXPERIENCE_ALLOWED_EXTENSIONS = [
  ADMIN_EXPERIENCE_EXTENSIONS.PNG,
  ADMIN_EXPERIENCE_EXTENSIONS.JPG,
  ADMIN_EXPERIENCE_EXTENSIONS.JPEG,
  ADMIN_EXPERIENCE_EXTENSIONS.WEBP,
] as const;

export const ADMIN_EXPERIENCE_ALLOWED_INPUT_ACCEPT =
  ADMIN_EXPERIENCE_ALLOWED_EXTENSIONS.map((ext) => `.${ext}`).join(",");

export const ADMIN_EXPERIENCE_ALLOWED_EXTENSIONS_READABLE =
  ADMIN_EXPERIENCE_ALLOWED_EXTENSIONS.join(", ");
