/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExperienciesRouteImport } from './routes/experiencies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiExperienciesRouteImport } from './routes/api/experiencies'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminExperienciesIndexRouteImport } from './routes/admin/experiencies/index'
import { Route as ApiProjectsSummaryRouteImport } from './routes/api/projects.summary'
import { Route as ApiProjectsSlugRouteImport } from './routes/api/projects.$slug'
import { Route as ApiExperienciesIdRouteImport } from './routes/api/experiencies.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminProjectsNewRouteImport } from './routes/admin/projects/new'
import { Route as AdminProjectsSlugRouteImport } from './routes/admin/projects/$slug'
import { Route as AdminExperienciesNewRouteImport } from './routes/admin/experiencies/new'
import { Route as AdminExperienciesIdRouteImport } from './routes/admin/experiencies/$id'

const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciesRoute = ExperienciesRouteImport.update({
  id: '/experiencies',
  path: '/experiencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExperienciesRoute = ApiExperienciesRouteImport.update({
  id: '/api/experiencies',
  path: '/api/experiencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExperienciesIndexRoute = AdminExperienciesIndexRouteImport.update({
  id: '/admin/experiencies/',
  path: '/admin/experiencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsSummaryRoute = ApiProjectsSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiProjectsSlugRoute = ApiProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiExperienciesIdRoute = ApiExperienciesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiExperienciesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/admin/projects/new',
  path: '/admin/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsSlugRoute = AdminProjectsSlugRouteImport.update({
  id: '/admin/projects/$slug',
  path: '/admin/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExperienciesNewRoute = AdminExperienciesNewRouteImport.update({
  id: '/admin/experiencies/new',
  path: '/admin/experiencies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExperienciesIdRoute = AdminExperienciesIdRouteImport.update({
  id: '/admin/experiencies/$id',
  path: '/admin/experiencies/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experiencies': typeof ExperienciesRoute
  '/login': typeof LoginRoute
  '/references': typeof ReferencesRoute
  '/api/experiencies': typeof ApiExperienciesRouteWithChildren
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/experiencies/$id': typeof AdminExperienciesIdRoute
  '/admin/experiencies/new': typeof AdminExperienciesNewRoute
  '/admin/projects/$slug': typeof AdminProjectsSlugRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/experiencies/$id': typeof ApiExperienciesIdRoute
  '/api/projects/$slug': typeof ApiProjectsSlugRoute
  '/api/projects/summary': typeof ApiProjectsSummaryRoute
  '/admin/experiencies/': typeof AdminExperienciesIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experiencies': typeof ExperienciesRoute
  '/login': typeof LoginRoute
  '/references': typeof ReferencesRoute
  '/api/experiencies': typeof ApiExperienciesRouteWithChildren
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/experiencies/$id': typeof AdminExperienciesIdRoute
  '/admin/experiencies/new': typeof AdminExperienciesNewRoute
  '/admin/projects/$slug': typeof AdminProjectsSlugRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/experiencies/$id': typeof ApiExperienciesIdRoute
  '/api/projects/$slug': typeof ApiProjectsSlugRoute
  '/api/projects/summary': typeof ApiProjectsSummaryRoute
  '/admin/experiencies': typeof AdminExperienciesIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experiencies': typeof ExperienciesRoute
  '/login': typeof LoginRoute
  '/references': typeof ReferencesRoute
  '/api/experiencies': typeof ApiExperienciesRouteWithChildren
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/experiencies/$id': typeof AdminExperienciesIdRoute
  '/admin/experiencies/new': typeof AdminExperienciesNewRoute
  '/admin/projects/$slug': typeof AdminProjectsSlugRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/experiencies/$id': typeof ApiExperienciesIdRoute
  '/api/projects/$slug': typeof ApiProjectsSlugRoute
  '/api/projects/summary': typeof ApiProjectsSummaryRoute
  '/admin/experiencies/': typeof AdminExperienciesIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/experiencies'
    | '/login'
    | '/references'
    | '/api/experiencies'
    | '/api/projects'
    | '/projects/$slug'
    | '/admin/'
    | '/projects/'
    | '/admin/experiencies/$id'
    | '/admin/experiencies/new'
    | '/admin/projects/$slug'
    | '/admin/projects/new'
    | '/api/auth/$'
    | '/api/experiencies/$id'
    | '/api/projects/$slug'
    | '/api/projects/summary'
    | '/admin/experiencies/'
    | '/admin/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/experiencies'
    | '/login'
    | '/references'
    | '/api/experiencies'
    | '/api/projects'
    | '/projects/$slug'
    | '/admin'
    | '/projects'
    | '/admin/experiencies/$id'
    | '/admin/experiencies/new'
    | '/admin/projects/$slug'
    | '/admin/projects/new'
    | '/api/auth/$'
    | '/api/experiencies/$id'
    | '/api/projects/$slug'
    | '/api/projects/summary'
    | '/admin/experiencies'
    | '/admin/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/experiencies'
    | '/login'
    | '/references'
    | '/api/experiencies'
    | '/api/projects'
    | '/projects/$slug'
    | '/admin/'
    | '/projects/'
    | '/admin/experiencies/$id'
    | '/admin/experiencies/new'
    | '/admin/projects/$slug'
    | '/admin/projects/new'
    | '/api/auth/$'
    | '/api/experiencies/$id'
    | '/api/projects/$slug'
    | '/api/projects/summary'
    | '/admin/experiencies/'
    | '/admin/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExperienciesRoute: typeof ExperienciesRoute
  LoginRoute: typeof LoginRoute
  ReferencesRoute: typeof ReferencesRoute
  ApiExperienciesRoute: typeof ApiExperienciesRouteWithChildren
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  AdminExperienciesIdRoute: typeof AdminExperienciesIdRoute
  AdminExperienciesNewRoute: typeof AdminExperienciesNewRoute
  AdminProjectsSlugRoute: typeof AdminProjectsSlugRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AdminExperienciesIndexRoute: typeof AdminExperienciesIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencies': {
      id: '/experiencies'
      path: '/experiencies'
      fullPath: '/experiencies'
      preLoaderRoute: typeof ExperienciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/experiencies': {
      id: '/api/experiencies'
      path: '/api/experiencies'
      fullPath: '/api/experiencies'
      preLoaderRoute: typeof ApiExperienciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/experiencies/': {
      id: '/admin/experiencies/'
      path: '/admin/experiencies'
      fullPath: '/admin/experiencies/'
      preLoaderRoute: typeof AdminExperienciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/summary': {
      id: '/api/projects/summary'
      path: '/summary'
      fullPath: '/api/projects/summary'
      preLoaderRoute: typeof ApiProjectsSummaryRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/projects/$slug': {
      id: '/api/projects/$slug'
      path: '/$slug'
      fullPath: '/api/projects/$slug'
      preLoaderRoute: typeof ApiProjectsSlugRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/experiencies/$id': {
      id: '/api/experiencies/$id'
      path: '/$id'
      fullPath: '/api/experiencies/$id'
      preLoaderRoute: typeof ApiExperienciesIdRouteImport
      parentRoute: typeof ApiExperienciesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/admin/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$slug': {
      id: '/admin/projects/$slug'
      path: '/admin/projects/$slug'
      fullPath: '/admin/projects/$slug'
      preLoaderRoute: typeof AdminProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/experiencies/new': {
      id: '/admin/experiencies/new'
      path: '/admin/experiencies/new'
      fullPath: '/admin/experiencies/new'
      preLoaderRoute: typeof AdminExperienciesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/experiencies/$id': {
      id: '/admin/experiencies/$id'
      path: '/admin/experiencies/$id'
      fullPath: '/admin/experiencies/$id'
      preLoaderRoute: typeof AdminExperienciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiExperienciesRouteChildren {
  ApiExperienciesIdRoute: typeof ApiExperienciesIdRoute
}

const ApiExperienciesRouteChildren: ApiExperienciesRouteChildren = {
  ApiExperienciesIdRoute: ApiExperienciesIdRoute,
}

const ApiExperienciesRouteWithChildren = ApiExperienciesRoute._addFileChildren(
  ApiExperienciesRouteChildren,
)

interface ApiProjectsRouteChildren {
  ApiProjectsSlugRoute: typeof ApiProjectsSlugRoute
  ApiProjectsSummaryRoute: typeof ApiProjectsSummaryRoute
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsSlugRoute: ApiProjectsSlugRoute,
  ApiProjectsSummaryRoute: ApiProjectsSummaryRoute,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExperienciesRoute: ExperienciesRoute,
  LoginRoute: LoginRoute,
  ReferencesRoute: ReferencesRoute,
  ApiExperienciesRoute: ApiExperienciesRouteWithChildren,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  ProjectsSlugRoute: ProjectsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  AdminExperienciesIdRoute: AdminExperienciesIdRoute,
  AdminExperienciesNewRoute: AdminExperienciesNewRoute,
  AdminProjectsSlugRoute: AdminProjectsSlugRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AdminExperienciesIndexRoute: AdminExperienciesIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
